<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBktg7f1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBktg7f1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBktg7f1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBktg7f1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBktg7f1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Bktg7f1',
    'container.build_id' => 'fec458fb',
    'container.build_time' => 1594398792,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBktg7f1');
