<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKB0tOOI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKB0tOOI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKB0tOOI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKB0tOOI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKB0tOOI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KB0tOOI',
    'container.build_id' => '96705409',
    'container.build_time' => 1592922844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKB0tOOI');
