<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7je6KVM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7je6KVM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7je6KVM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7je6KVM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7je6KVM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7je6KVM',
    'container.build_id' => 'd1effe2c',
    'container.build_time' => 1594815962,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7je6KVM');
